### PR TITLE
Update 'Overview of Features' section of User Guide'

### LINKED ISSUE #12: Update "Overview of Features" Section of User Guide
Move the draft UG content into the User Guide page in your repository. Update the content as necessary. If a feature is not implemented in the current version, you can either omit it from the UG or mark it as 'Coming soon'.

### PR DESCRIPTION
**Pull request by joshenx**
Closes #12

### CODE REVIEW

**Comment by joshenx** [comment]
Hi, note that Files changed may appear messy because I removed all unnecessary trailing and preceding whitespaces. This should not negatively affect the formatting of the User Guide.

**Review by gycgabriel — APPROVED** [review]
LGTM

**Review by didymental — APPROVED** [review]
LGTM

**Comment by didymental** [comment]
This PR resolves #42

**Pull request merged**
